<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerYbbv5U6\srcApp_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerYbbv5U6/srcApp_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerYbbv5U6.legacy');

    return;
}

if (!\class_exists(srcApp_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerYbbv5U6\srcApp_KernelDevDebugContainer::class, srcApp_KernelDevDebugContainer::class, false);
}

return new \ContainerYbbv5U6\srcApp_KernelDevDebugContainer([
    'container.build_hash' => 'Ybbv5U6',
    'container.build_id' => 'c1f7d045',
    'container.build_time' => 1578760987,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerYbbv5U6');
